from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, re_path, reverse_lazy
from django.views.generic import TemplateView
from django_registration.backends.activation.views import (
    RegistrationView,
)

from .forms import CompanyRegistrationForm, RegistrationForm
from .views import (
    AccountPage,
    ActivationView,
    PasswordChangeView,
    PasswordResetConfirmView,
    PasswordResetView,
    CompanyApprovalPendingList,
    CompanyApproveView,
    UserList,
)

urlpatterns = [
    path("account/", AccountPage.as_view(), name="account"),
    path(
        "login/",
        LoginView.as_view(template_name="user/login.html"),
        name="login",
    ),
    path(
        "logout/",
        LogoutView.as_view(
            template_name="user/logout.html"
        ),
        name="logout",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password_reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^activate/(?P<activation_key>[-:\w]+)/$",
        ActivationView.as_view(),
        name="django_registration_activate",
    ),
    path(
        "register/",
        RegistrationView.as_view(
            form_class=RegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_complete"
            ),
        ),
        name="django_registration_register",
    ),
    path(
        "register/complete/",
        TemplateView.as_view(
            template_name="django_registration/registration_complete.html"
        ),
        name="django_registration_complete",
    ),
    path(
        "register/closed/",
        TemplateView.as_view(
            template_name="django_registration/registration_closed.html"
        ),
        name="django_registration_disallowed",
    ),
    path(
        "register_company/",
        RegistrationView.as_view(
            form_class=CompanyRegistrationForm,
            success_url=reverse_lazy(
                "auth:django_registration_company_complete"
            ),
        ),
        name="django_registration_register_company",
    ),
    path(
        "register_company/complete/",
        TemplateView.as_view(
            template_name="django_registration/company_registration_complete.html"
        ),
        name="django_registration_company_complete",
    ),
    path(
        "companies_pending_approval/",
        CompanyApprovalPendingList.as_view(),
        name="django_approval_pending_companies",
    ),
    path(
        "approve_company/<int:pk>/",
        CompanyApproveView.as_view(),
        name="django_approve_company",
    ),
    path(
        "user/",
        UserList.as_view(),
        name="django_list_users"
    )
]
